import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"
import Navigation from "@/components/Navigation";
import Logo from "@/components/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // title: "The Maclo Cottages",
  title:{
    template:"%s | The Maclo Cottages",
    default:"Welcome | The Maclo Cottages"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-primary-950 text-primary-100  min-h-screen`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Logo/>
        <Navigation />
        </header>
        <main>
           {children}
        </main>
        
        </body>
    </html>
  );
}
